e_APTdata<-function(explaining=0){
if(explaining==0) {
cat(" ## DATA : 부동산 실거래 공개시스템(http://rt.molit.go.kr)", '\n')
cat("", '\n')
cat("library(readxl)", '\n')
cat("library(dplyr)", '\n')
cat("", '\n')
cat("# Adata<-read_excel('APT수지구.xlsx')", '\n')
cat("", '\n')
cat("a17<-read_excel('APT매매경기도2017.xlsx', skip=15)", '\n')
cat("a17<-a17[,c(1:11)]", '\n')
cat("a18<-read_excel('APT매매경기도2018.xlsx', skip=15)", '\n')
cat("a18<-a18[,c(1:11)]", '\n')
cat("a19<-read_excel('APT매매경기도2019.xlsx', skip=15)", '\n')
cat("a19<-a19[,c(1:11)]", '\n')
cat("a20<-read_excel('APT매매경기도2020.xlsx', skip=15)", '\n')
cat("a20<-a20[,c(1:11)]", '\n')
cat("a21<-read_excel('APT매매경기도2021.xlsx', skip=15)", '\n')
cat("a21<-a21[,c(1:11)]", '\n')
cat("a22<-read_excel('APT매매경기도2022.xlsx', skip=15)", '\n')
cat("a22<-a22[,c(1:11)]", '\n')
cat("", '\n')
cat("Adata<-rbind(a17, a18, a19, a20, a21, a22)", '\n')
cat("Adata<-as.data.frame(Adata)", '\n')
cat("rm(a17, a18, a19, a20, a21, a22)", '\n')
cat("Adata<-Adata[,c(1, 5:11)]", '\n')
cat("", '\n')
cat("# 이후의 데이터마이닝은 생략 ", '\n')
cat("", '\n')
cat("colnames(Adata)<-c('시군구','단지명','전용면적','계약년월','계약일','거래금액','층', '건축연도' )", '\n')
cat("Adata$평형<- round(Adata$전용면적/3.3, 0)", '\n')
cat("Adata$평당매매가<-round(Adata$거래금액/(Adata$전용면적/3.3), 0)", '\n')
cat("# colnames(Adata)", '\n')
cat("# [1] 시군구     단지명     전용면적   계약년월   계약일     거래금액  ", '\n')
cat("# [7] 층        건축연도    year     평형      평당매매가          ", '\n')
cat("", '\n')
cat("Bdata <-Adata%>%filter( grepl('상현동', 시군구) & grepl('광교상록자이', 단지명) )", '\n')
cat("Bdata<-as.data.frame(Bdata)", '\n')
cat("Cdata<-Bdata%>%group_by(평형, 계약년월)%>%summarize( 평당매매가평균=mean(평당매매가), 거래횟수=n())", '\n')
cat("", '\n')
cat("##################################################", '\n')
cat("temp1<-sort(unique(Adata$계약년월))", '\n')
cat("count0<-length(temp1)", '\n')
cat("", '\n')
cat("# 시작 YearMonth", '\n')
cat("temp1[1]", '\n')
cat("", '\n')
cat("# 마지막 YearMonth", '\n')
cat("temp1[count0]", '\n')
cat("", '\n')
cat("# temp1[1]을 그대로 입력", '\n')
cat("# Start YearMonth, (예:201701) ", '\n')
cat("ans0 <- '201701' ", '\n')
cat("", '\n')
cat("# temp1[1]을 참조해 Day를 01로 지정", '\n')
cat("# Start Year-Month-Day, (예:2017-01-01)", '\n')
cat("ans1<-'2017-01-01' ", '\n')
cat("", '\n')
cat("# temp1[count0]을 참조해 Day를 30 또는, 31로 지정", '\n')
cat("# End Year-Month-Day, (예:2021-12-31)", '\n')
cat("ans2<- '2021-12-31'  ", '\n')
cat("", '\n')
cat("", '\n')
cat("elapsed_months <- function(start_date, end_date) {", '\n')
cat("    ed <- as.POSIXlt(end_date)", '\n')
cat("    sd <- as.POSIXlt(start_date)", '\n')
cat("    12 * (ed$year - sd$year) + (ed$mon - sd$mon)", '\n')
cat("}", '\n')
cat("", '\n')
cat("", '\n')
cat("CNT <-elapsed_months(ans1, ans2) + 1", '\n')
cat("ans0<-as.numeric(ans0)", '\n')
cat("year0 <-as.numeric( substring(ans0, 1, 4) )", '\n')
cat("month0 <-as.numeric( substring(ans0, 5, 6) )", '\n')
cat("", '\n')
cat("Bdata<-as.data.frame( matrix(NA, nrow=CNT) )", '\n')
cat("Bdata$V1<-NA; Bdata$V2<-NA; Bdata$V3<-NA; Bdata$V4<-NA; Bdata$V5<-NA; ", '\n')
cat("Bdata$V6<-NA; Bdata$V7<-NA; Bdata$V8<-NA; Bdata$V9<-NA", '\n')
cat("", '\n')
cat("r=c()", '\n')
cat("", '\n')
cat("for(i in 1:CNT){", '\n')
cat("month1<-month0", '\n')
cat("if(month1<10) {month1<-paste0('0', month1)}", '\n')
cat("else {month1<-as.character(month1)}", '\n')
cat("TempDate<-as.numeric(paste0(year0, month1))", '\n')
cat("r=c(r, TempDate)", '\n')
cat("if(month0==12) {year0 <- year0 + 1", '\n')
cat("month0<-0}", '\n')
cat("month0<-month0+1 }", '\n')
cat("", '\n')
cat("timeindex <- r", '\n')
cat("", '\n')
cat("##############################################################################", '\n')
cat("colnames(Cdata)<-c('평형','계약년월','평당매매가평균', '거래횟수')", '\n')
cat("xtabs(~Cdata$평형)", '\n')
cat("평형index<-as.numeric(names(xtabs(~Cdata$평형)))", '\n')
cat("평형인덱스<-평형index", '\n')
cat("", '\n')
cat("TempCount <- length(평형index)", '\n')
cat("", '\n')
cat("Temp<-as.data.frame(matrix(data=rep(c(NA),(TempCount*CNT)*4), ncol=4))", '\n')
cat("colnames(Temp)<-c('평형','계약년월','평당매매가평균', '거래횟수')", '\n')
cat("", '\n')
cat("for(kM in 1:TempCount){", '\n')
cat("alpha <- kM*CNT-(CNT-1)", '\n')
cat("beta <- kM*CNT", '\n')
cat("for(iM  in  alpha: beta ){", '\n')
cat("Temp$평형[iM] <- 평형index[kM]", '\n')
cat("}}", '\n')
cat("", '\n')
cat("for(kM in 1:TempCount){", '\n')
cat("alpha <- kM*CNT-(CNT-1)", '\n')
cat("beta <- kM*CNT", '\n')
cat("for(iM  in  alpha: beta ){", '\n')
cat("Temp$계약년월[iM] <- timeindex[iM-(kM-1)*CNT]", '\n')
cat("}}", '\n')
cat("", '\n')
cat("", '\n')
cat("TempCount2 <- (TempCount * CNT )", '\n')
cat("", '\n')
cat("for( j in 1:TempCount2) {", '\n')
cat("for( i in 1:nrow(Cdata) ) {", '\n')
cat("if(Temp$평형[j]==Cdata$평형[i]  & Temp$계약년월[j]==Cdata$계약년월[i] )", '\n')
cat("{Temp$평당매매가평균[j] <- Cdata$평당매매가평균[i] ", '\n')
cat(" Temp$거래횟수[j] <- Cdata$거래횟수[i] } }}", '\n')
cat("", '\n')
cat("평형인덱스", '\n')
cat("", '\n')
cat("##################################################################", '\n')
cat("## 최초의 데이터가 NA일 때를 고려한 조치방안", '\n')
cat("## Temp 데이터셋의 자료를 보고 각 평형대가 시작하는 최초의 데이터가 NA이면", '\n')
cat("## 가장 가까운 값을 가져와서 최초의 데이터값을 채워 넣는다.", '\n')
cat("## 현대성우3차의 경우는 다음과 같다.", '\n')
cat("## Temp[,3][1]<-Temp[,3][5]", '\n')
cat("## Temp[,3][61]<-Temp[,3][63]", '\n')
cat("## Temp[,3][121]<-Temp[,3][135]", '\n')
cat("", '\n')
cat("## NA이면 이전 데이터값으로 채워넣기", '\n')
cat("Temp[,3]<-zoo::na.locf(Temp[,3])", '\n')
cat("", '\n')
cat("## Plotting 전단계  ", '\n')
cat("colnames(Temp)<-c('pyung','contday','price', 'freqTrading')", '\n')
cat("Temp$contyear<-substr(Temp$contday, 1,4)", '\n')
cat("Temp$contmonth<-substr(Temp$contday, 5,6)", '\n')
cat("Temp$contdate0<-paste0(Temp$contyear, '-',Temp$contmonth, '-01')", '\n')
cat("Temp$contdate0<-as.Date(Temp$contdate0)", '\n')
cat("", '\n')
cat("### 수정해야 할 부분: pyung ==", '\n')
cat("plot( subset( Temp,  pyung==31, select = c( contdate0, price ) ) , type='l', ylim=c(500, 2600))", '\n')
cat("par(new=T)", '\n')
cat("plot( subset( Temp,  pyung==42, select = c( contdate0, price ) ) , type='l', ylim=c(500, 2600), col='blue', xlab='', ylab='' )", '\n')
cat("par(new=T)", '\n')
cat("plot( subset( Temp,  pyung==56, select = c( contdate0, price ) ) , type='l', ylim=c(500, 2600), col='red', xlab='', ylab='' )", '\n')
cat("", '\n')
}}


