e_APTdata<-function(explaining=0){
if(explaining==0) {
cat(" ## DATA : 부동산 실거래 공개시스템(http://rt.molit.go.kr)", '\n')
cat("##################################################  ", '\n')
cat("# 데이터셋명 교체.. 아래 for문을 콘솔에 복사해 실행시키면 명령문이 생성된다. ", '\n')
cat("# for(i in 1:no_data){ ", '\n')
cat("# print( paste('if(counterxx==', i, ') {A', i, '<-Temp }', sep='') )  } ", '\n')
cat("# Temp를 데이터셋으로 변경시키는 명령문을 복사해 맨 끝에 붙여놓으면 끝~~~ ", '\n')
cat(" ", '\n')
cat("if(counterxx==1) {A1<-Temp } ", '\n')
cat("if(counterxx==2) {A2<-Temp } ", '\n')
cat("---- 생략 ---- ", '\n')
cat("if(counterxx==55) {A55<-Temp } ", '\n')
cat("if(counterxx==56) {A56<-Temp } ", '\n')
cat("##################################################  ", '\n')
cat("", '\n')
cat("library(readxl) ", '\n')
cat("library(dplyr) ", '\n')
cat(" ", '\n')
cat("a15<-read_excel('APT매매경기도2015.xlsx', skip=15) ", '\n')
cat("a15<-a15[,c(1:11)]  ", '\n')
cat("a16<-read_excel('APT매매경기도2016.xlsx', skip=15)  ", '\n')
cat("a16<-a16[,c(1:11)] ", '\n')
cat("a17<-read_excel('APT매매경기도2017.xlsx', skip=15)  ", '\n')
cat("a17<-a17[,c(1:11)]  ", '\n')
cat("a18<-read_excel('APT매매경기도2018.xlsx', skip=15)  ", '\n')
cat("a18<-a18[,c(1:11)]  ", '\n')
cat("a19<-read_excel('APT매매경기도2019.xlsx', skip=15)  ", '\n')
cat("a19<-a19[,c(1:11)]  ", '\n')
cat("a20<-read_excel('APT매매경기도2020.xlsx', skip=15)  ", '\n')
cat("a20<-a20[,c(1:11)]  ", '\n')
cat("a21<-read_excel('APT매매경기도2021.xlsx', skip=15)  ", '\n')
cat("a21<-a21[,c(1:11)]  ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("Adata<-rbind(a15, a16, a17, a18, a19, a20, a21)  ", '\n')
cat("Adata<-as.data.frame(Adata)  ", '\n')
cat("rm(a15, a16, a17, a18, a19, a20, a21)  ", '\n')
cat("Adata<-Adata[,c(1, 5:11)]  ", '\n')
cat(" ", '\n')
cat("colnames(Adata)<-c('시군구','단지명','전용면적','계약년월','계약일','거래금액','층', '건축연도' )  ", '\n')
cat("Adata$전용면적<-as.numeric( Adata$전용면적 ) ", '\n')
cat("Adata$평형<- round(Adata$전용면적/3.3, 0)  ", '\n')
cat(" ", '\n')
cat("Adata$거래금액 <- gsub(',', '', Adata$거래금액) ", '\n')
cat("Adata$거래금액<-as.numeric( Adata$거래금액 ) ", '\n')
cat("Adata$평당매매가<-round(Adata$거래금액/(Adata$전용면적/3.3), 0)  ", '\n')
cat(" ", '\n')
cat("SE_day<-function(Sday, mark=1){ ", '\n')
cat("  if(mark==1) {paste(substring(Sday,1,4), '-', substring(Sday,5,6), '-','01', sep='')} ", '\n')
cat("  else if(mark==2) {paste(substring(Sday,1,4), '-', substring(Sday,5,6), '-','31', sep='')} ", '\n')
cat("} ", '\n')
cat(" ", '\n')
cat("ym_data<-sort(unique(Adata$계약년월))  # 시작 YearMonth  ", '\n')
cat("start_yearmonth<-ym_data[1] ", '\n')
cat("end_yearmonth<-ym_data[length(ym_data)]  # 마지막 YearMonth  ", '\n')
cat(" ", '\n')
cat("start_yearmonthday<-SE_day(start_yearmonth, 1) ", '\n')
cat("end_yearmonthday<-SE_day(end_yearmonth,2) ", '\n')
cat(" ", '\n')
cat("elapsed_months <- function(start_date, end_date) {  ", '\n')
cat("  ed <- as.POSIXlt(end_date)  ", '\n')
cat("  sd <- as.POSIXlt(start_date)  ", '\n')
cat("  12 * (ed$year - sd$year) + (ed$mon - sd$mon +1 ) ", '\n')
cat("}  ", '\n')
cat(" ", '\n')
cat("total_elapsed_months <- elapsed_months(start_yearmonthday, end_yearmonthday) ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("library(dplyr) ", '\n')
cat(" ", '\n')
cat("## 아파트에 대한 정의 ", '\n')
cat("aptname <- Adata%>%filter( grepl('상현동', 시군구))  ", '\n')
cat("aptname<-unique(aptname$단지명) ", '\n')
cat("no_data<-length(aptname) ", '\n')
cat(" ", '\n')
cat("# aptname을 사용해 아파트별 데이터셋을 만들자 ", '\n')
cat("# counterxx의 숫자를 counterxx의 총숫자에 맞춰 변경시키면서 자료를 만들자. ", '\n')
cat("# 아파트명은 aptname에 기록되어 있다. ", '\n')
cat(" ", '\n')
cat("for( counterxx in 1:no_data) { ", '\n')
cat(" ", '\n')
cat("# loop를 타기 앞서서 실험적으로 시행하자 ", '\n')
cat(" ", '\n')
cat("Bdata <-Adata%>%filter( grepl('상현동', 시군구) & grepl(aptname[counterxx], 단지명) ) ", '\n')
cat("if(nrow(Bdata)==0) {next} ", '\n')
cat(" ", '\n')
cat("# 아파트는 광교강남아너스빌인 데, 평형대가 다양하다. 평형대를 골라내자 ", '\n')
cat("summary_data<-Bdata%>%group_by(평형, 계약년월)%>%summarize( 평당매매가평균=mean(평당매매가, na.rm=T), 거래횟수=n())  ", '\n')
cat("summary_data<-as.data.frame(summary_data) ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("## 최소평형 한 개만 고른다. 만약 여러 평형을 조사하고 싶다면 datacollect로 자료를 병렬로 저장할 수 없다. ", '\n')
cat("## 개별로 데이터를 저장해야 한다 ", '\n')
cat("## 아파트들 중 최소 평형만 골라서 데이터셋을 만들려면  ", '\n')
cat("## pyung<-min(unique(Bdata$평형)) 명령문을 사용한다. ", '\n')
cat("pyung<-unique(Bdata$평형) ", '\n')
cat(" ", '\n')
cat("pyung_counter<-length(pyung) ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("## Cdata의 계약년월에 들어갈 자료 만들기 -- 시작 ", '\n')
cat("year0 <-as.numeric( substring(start_yearmonth, 1, 4) ) ", '\n')
cat("month0 <-as.numeric( substring(start_yearmonth, 5, 6) ) ", '\n')
cat(" ", '\n')
cat("CNT <- total_elapsed_months ## 총개월수인 데, total_elapsed_months를 지정할 때 ", '\n')
cat("# 아파트 평형대는 최솟값 한 개를 지정하면 CNT는 84로 고정된다. ", '\n')
cat("# CNT가 84 이상이면 데이터를 병렬로 연결하는 것은 .... 좀... 어렵다 ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("timeindex=c()  ", '\n')
cat("for(i in 1:CNT){  ", '\n')
cat("  month1<-month0  ", '\n')
cat("  if(month1<10) {month1<-paste0('0', month1)}  ", '\n')
cat("  else {month1<-as.character(month1)}  ", '\n')
cat("  TempDate<-as.numeric(paste0(year0, month1))  ", '\n')
cat("   ", '\n')
cat("  timeindex=c(timeindex, TempDate)  ", '\n')
cat("   ", '\n')
cat("  if(month0==12) {year0 <- year0 + 1  ", '\n')
cat("  month0<-0}  ", '\n')
cat("  month0<-month0+1 }  ", '\n')
cat("## timeindex 변수의 완성 ", '\n')
cat("## Cdata의 계약년월에 들어갈 timeindex자료 만들기 -- 끝 ", '\n')
cat("## timeindex를 Cdata의 계약년월에 대입하자 ", '\n')
cat(" ", '\n')
cat("colnames(summary_data)<-c('평형','계약년월','평당매매가평균', '거래횟수')  ", '\n')
cat("평형index<-as.numeric(names(xtabs(~summary_data$평형))) ", '\n')
cat("TempCount <- length(평형index) ", '\n')
cat(" ", '\n')
cat("Temp<-as.data.frame(matrix(data=rep(c(NA),(TempCount*CNT)*5), ncol=5))  ", '\n')
cat("colnames(Temp)<-c('아파트', '평형','계약년월','평당매매가평균', '거래횟수' )  ", '\n')
cat(" ", '\n')
cat("for(kM in 1:TempCount){  ", '\n')
cat("  alpha <- kM*CNT-(CNT-1)  ", '\n')
cat("  beta <- kM*CNT  ", '\n')
cat("  for(iM  in  alpha: beta ){  ", '\n')
cat("    Temp$아파트[iM] <- aptname[counterxx]  ", '\n')
cat("  }}  ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("for(kM in 1:TempCount){  ", '\n')
cat("  alpha <- kM*CNT-(CNT-1)  ", '\n')
cat("  beta <- kM*CNT  ", '\n')
cat("  for(iM  in  alpha: beta ){  ", '\n')
cat("    Temp$평형[iM] <- 평형index[kM]  ", '\n')
cat("  }}  ", '\n')
cat(" ", '\n')
cat("for(kM in 1:TempCount){  ", '\n')
cat("  alpha <- kM*CNT-(CNT-1)  ", '\n')
cat("  beta <- kM*CNT  ", '\n')
cat("  for(iM  in  alpha: beta ){  ", '\n')
cat("    Temp$계약년월[iM] <- timeindex[iM-(kM-1)*CNT]  ", '\n')
cat("  }}  ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("TempCount2 <- (TempCount * CNT ) ", '\n')
cat(" ", '\n')
cat("for( j in 1:TempCount2) {  ", '\n')
cat("  for( i in 1:nrow(summary_data) ) {  ", '\n')
cat("    if(Temp$평형[j]==summary_data$평형[i]  & Temp$계약년월[j]==summary_data$계약년월[i] )  ", '\n')
cat("    {Temp$평당매매가평균[j] <- summary_data$평당매매가평균[i]   ", '\n')
cat("    Temp$거래횟수[j] <- summary_data$거래횟수[i] } } } ", '\n')
cat(" ", '\n')
cat("colnames(Temp)[1]<-paste('apt',counterxx, sep='' ) ", '\n')
cat("colnames(Temp)[2]<-paste('py',counterxx, sep='' ) ", '\n')
cat("colnames(Temp)[3]<-paste('contDATE',counterxx, sep='' ) ", '\n')
cat("colnames(Temp)[4]<-paste('price_py',counterxx, sep='' ) ", '\n')
cat("colnames(Temp)[5]<-paste('frequ',counterxx, sep='' ) ", '\n')
cat(" ", '\n')
cat(" ", '\n')
cat("##################################################  ", '\n')
cat("# 데이터셋명 교체.. 아래 for문을 콘솔에 복사해 실행시키면 명령문이 생성된다. ", '\n')
cat("# for(i in 1:no_data){ ", '\n')
cat("# print( paste('if(counterxx==', i, ') {A', i, '<-Temp }', sep='') )  } ", '\n')
cat("# Temp를 데이터셋으로 변경시키는 명령문만 복사해 붙여넣기하면 끝~~~ ", '\n')
cat(" ", '\n')
cat("if(counterxx==1) {A1<-Temp } ", '\n')
cat("if(counterxx==2) {A2<-Temp } ", '\n')
cat("---- 생략 ---- ", '\n')
cat("if(counterxx==55) {A55<-Temp } ", '\n')
cat("if(counterxx==56) {A56<-Temp } ", '\n')
cat("##################################################  ", '\n')
cat(" ", '\n')
cat("} ", '\n')
cat(" ", '\n')
}}


