e_datamining<-function(explaining=0){

if(explaining==0) {
cat("   ", '\n')
cat("\033[1;31m## 화면 스크롤 갯수 확대 & 미싱데이터 채우기 -------\033[0m ", '\n')
cat("  print(tmp, n=9999)  ", '\n')
cat("  options(max.print=9999)  ", '\n')
cat("  options(dplyr.print_max=9999)  ", '\n')
cat("  zoo::na.locf(df) \033[1;31m미싱데이터값을 이전 값으로 채우기\033[0m ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## CSV파일과 Excel파일 로딩하기 -------  \033[0m", '\n')
cat("  library(aj412s) ", '\n')
cat("  df<-opencsv('csv파일.csv', header=T, skip=1) \033[1;31m데이터프레임data.frame으로 저장\033[0m", '\n')
cat("  df<-openxlsx('엑셀파일.xlsx', header=T, skip=1) \033[1;31m데이터프레임data.frame으로 저장\033[0m", '\n')
cat("  df<-as.data.frame(df) \033[1;31m데이터를 데이터프레임으로 재지정\033[0m", '\n')
cat("   ", '\n')
cat("\033[1;31m## 데이터프레임의 특정 변수 지우기 ------- \033[0m", '\n') 
cat("  df <- df[ , -c(2, 4:5)] ", '\n')
cat("  head(df)  \033[1;31m레코드 6개 화면출력\033[0m", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 범주형변수:명목변수(성별.종교)/서열변수(학력.반등수)\033[0m ", '\n')
cat("\033[1;31m## 연속형변수:등간격변수(설문5점척도.IQ.온도)/비율변수(경력.시간.거리)\033[0m ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 통계 데이터형태 및 변수유형  -------- \033[0m ", '\n')
cat("   df<-as.data.frame(df)  \033[1;31m데이터프레임-통계 데이터형태\033[0m", '\n')
cat("   df$gender<-as.factor(df$gender)  \033[1;31m요인-범주형변수\033[0m", '\n')
cat("   df$ind<-as.character(df$ind)  \033[1;31m문자-범주형변수\033[0m", '\n')
cat("   df$ind<-as.numeric(df$ind)  \033[1;31m숫자-연속형변수\033[0m", '\n')
cat("   ", '\n')
cat("\033[1;31m## 2번째~4번째 컬럼 변수를 numeric 변수로 한꺼번에 바꾸기 -------- \033[0m ", '\n')
cat("   index<-c(2:4) ", '\n')
cat("   df[ ,index]<-lapply(df[,index], as.numeric) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## NA미싱데이터 삭제하기 ------- \033[0m", '\n')
cat("  df<-df[complete.cases(df), ] ", '\n')
cat("  df<-df[complete.cases(df$conv, df$satprice), ] ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## NA미싱데이터를 삭제하지 않은 자료에 NA가 있으면, na.rm=T 사용 ------- \033[0m  ", '\n')
cat("  mean(df$inc, na.rm=T)  ", '\n')
cat("  sd(df$inc, na.rm=T) ", '\n')
cat("  library(dplyr) ", '\n')
cat("  df%>%summarize(평균=mean(inc, na.rm=T)) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 기술통계 with jmv ------- \033[0m ", '\n')
cat("  library(aj412s) ", '\n')
cat("  df<-BasicData ", '\n')
cat("  df$gender<-as.factor(df$gender) ", '\n')
cat("   ", '\n')
cat("jmv::descriptives(  ", '\n')
cat("  data = df, ", '\n')
cat("  vars = c(gender, inc, debt), ", '\n')
cat("  skew = FALSE,  ", '\n')
cat("  kurt = FALSE, ", '\n')
cat("  freq = TRUE, ", '\n')
cat("  bar = TRUE, ", '\n')
cat("  dens = TRUE, ", '\n')
cat("  hist = TRUE, ", '\n')
cat("  violin = TRUE) ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## xtabs를 사용해 막대그래프 그리기 -------\033[0m ", '\n')
cat("  xtabs(~df$gender+df$brand)  ", '\n')
cat("  barplot(xtabs(~df$gender+df$brand), beside=T, horiz=F, ylab='빈도수', col=c('steelblue', 'salmon3'))  ", '\n')
cat("   ", '\n')


invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## dplyr사용법 ------- \033[0m", '\n')
cat("  df %>% group_by(브랜드)  ", '\n')
cat("        %>% summarize(편의성평균=mean(conv, na.rm=T),   ", '\n')
cat("        편의성표준편차=sd(conv, na.rm=T), 자료수=n(), .groups='drop_last')  ", '\n')
cat("   ", '\n')
cat("  df %>% select(brand, gender)  \033[1;31m변수 솎아내기 \033[0m", '\n')
cat("   ", '\n')
cat("  df %>% filter(brand=='KIA' & (debt>0 | gender==1) )  \033[1;31m레코드 필터링\033[0m", '\n')
cat("   ", '\n')
cat("  df %>% mutate(new_col=debt/inc)  \033[1;31m새로운 변수 만들기\033[0m", '\n')
cat("   ", '\n')
cat("  df %>% arrange(age, edu)  \033[1;31m age/edu변수를 기준으로 오름차순정렬/desc(age)내림차순정렬 \033[0m", '\n')
cat("   ", '\n')
cat("  NEWDATA<-merge(data1, data2, by='index') %>% merge(data3, by='index') ", '\n')
cat("      ", '\n')
cat("  df<-rename(df, 새변수명=편의성)  \033[1;31m변수명 변경은 colnames()로 변경하는 것을 권장함\033[0m ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 변수명 변경 -------\033[0m ", '\n')
cat("  df2<-BasicData[,c(1,3,7:10)] \033[1;31maj412s의 내장데이터BasicData를 df2로 저장\033[0m", '\n')
cat("  colnames(df2)<-c('id','brand','conv','satprice','age','gender') ", '\n')
cat("  colnames(df2)[6]<-c('성별') ", '\n')
cat("   ", '\n')


invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  library(aj412s) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 레코드 재코딩 -------- \033[0m", '\n')
cat("  df<-recoding(df, 열번호) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 더미변수 만들기 -------- \033[0m", '\n')
cat("  df<-mkdum(df, 열번호)   \033[1;31m변수명dum_1~변수명dum_n 생성 \033[0m ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 그룹변수 만들기 ------- \033[0m", '\n')
cat("  cn<-quantile(df$inc, c(.25, .5, .75) , na.rm=T) ", '\n')
cat("  df <- mkgroup(df, 14, cn) g_inc생성 ", '\n')
cat("  \033[1;31m또는 cn값을 직접 입력... \033[0m", '\n')
cat("  cn<-c(200, 300, 400, 500) ", '\n')
cat("  df <- mkgroup(df, 13, cn)  \033[1;31mg_expend생성\033[0m ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 로그를 취한 변수 만들기 --------\033[0m ", '\n')
cat("  df<-mklog(df, 14) \033[1;31minc변수에 로그를 취해 log_inc생성\033[0m", '\n')
cat("   ", '\n')
cat("\033[1;31m## 문자 레코드를 숫자로 바꾸기 --------\033[0m ", '\n')
cat("  df$brand2<-c2n(df$brand) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 코드값 재코딩 -------\033[0m ", '\n')
cat("  library(aj412s) ", '\n')
cat("   ", '\n')
cat("  \033[1;31m## 방법1 ------ \033[0m", '\n')
cat("  library(dplyr) ", '\n')
cat("  df$housing_se <- recode(df$housing, 'old1'='new1', 'old2'='new2') ", '\n')
cat("  또는 ... ", '\n')
cat("  df<-recoding(df, 7) ", '\n')
cat("   ", '\n')
cat("  \033[1;31m## 방법2 ------\033[0m ", '\n')
cat("  df$gender2[df$gender==1] <- 1  \033[1;31mgender의 코딩값을 재코딩해 gender2로 저장\033[0m ", '\n')
cat("  df$gender2[df$gender==2] <- 0 ", '\n')
cat("  df[df==''] <- NA  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 자료를 솎아내서 새데이터 만들기 -------\033[0m ", '\n')
cat("  df2 <- df[ complete.cases(df$conv, df$satprice, df$age), ]  ", '\n')
cat("  df2 <- df[ df$debtratio !=Inf , ] ", '\n')
cat("  df2 <- df[ !is.na(df$debtratio) , ] ", '\n')
cat("  df2 <- df[ df$debtratio <= 124 , ] ", '\n')
cat("   ", '\n')


invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 일부 변수를 선택해 새데이터셋 만들기 ------- \033[0m", '\n')
cat("  index <- c(2,4:6) ", '\n')
cat("  df2 <- df[ , index] ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 자료수 확인 ------- \033[0m", '\n')
cat("  sum(is.na(df$conv))  ", '\n')
cat("  sum(!is.na(df$conv))  ", '\n')
cat("  sum(df$brand=='Ford') ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 자료의 Sampling -------\033[0m ", '\n')
cat("  index2<-sample(nrow(df), 6, replace=F) ", '\n')
cat("  샘플데이터[index2 , ] ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## density그래프 그리기 -------\033[0m ", '\n')
cat("  ggplot(df, aes(x=inc)) + geom_density() ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## df$시군구 변수에서 용인수지구 단어가 있는 레코드를 솎아내기 ------ \033[0m", '\n')
cat("  df%>%filter( grepl('용인수지구' , df$시군구)) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 상현동 아파트들 중 상떼빌 아파트만 솎아내기 ------\033[0m ", '\n')
cat("  df%>%filter( grepl('상현동', df$시군구) & grepl('상떼빌', df$단지명)) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## subset명령문활용 --------\033[0m ", '\n')
cat("  subset(df, 평형==32, select=c(date0, 평당매매가평균)) ", '\n')
cat("  subset(df, (brand=='KIA' | brand=='GM') ,select=c(1,2,3,4)) ", '\n')
cat("  subset(df, grepl('KI', df$brand) ,select=c(1,2,3,4)) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## subset으로 32평의 평당매매가평균을 하나의 그래프로 그리기 --------\033[0m ", '\n')
cat("  plot(subset(df, 평형==32, select=c(date0, 평당매매가평균)), type='l', ", '\n')
cat("       col='cornflowerblue', lwd=2, ylim=c(1000, 2800)) ", '\n')
cat("  par(new=T) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## subset을 이용해 특정 레코드만 솎아내서 회귀분석하기 --------\033[0m ", '\n')
cat("  결과 <- lm(거래금액~전용면적+층, data=df, \033[1;93msubset=c(year==2021 & 평형==32)\033[0m  ) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m##확률 및 p값 --------\033[0m ", '\n')
cat("  t분포 경계값: qt(확률, n-1)  ", '\n')
cat("  \033[1;93mt분포 p값찾기\033[0m: 1-pt(t검정통계량, n-1)  ", '\n')
cat("  카이자승 경계값: qchisq(확률, 자유도)  ", '\n')
cat("  \033[1;93m카이자승 p값찾기\033[0m: 1-pchisq(카이자승_검정통계량, 자유도)  ", '\n')
cat("  F분포 경계값: qf(확률, 자유도1, 자유도2)  ", '\n')
cat("  \033[1;93mF분포 p값찾기\033[0m: 1-pf(F검정통계량, k-1, n-k)  ", '\n')
cat("  정규분포 확률 : pnorm(z검정통계량)  ", '\n')
cat("  정규분포 경계값: qnorm(확률)  ", '\n')
cat("  \033[1;93m정규분포 p값찾기\033[0m: 1-pnorm(z검정통계량)  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## wald test ------ \033[0m  ", '\n')
cat("  fit<-lm(inc~debt+house+spouse2, data=Adata) ", '\n')
cat("  linearHypothesis(fit, c('debt=3', 'spouse2+debt3<=10')) ", '\n')
cat("  linearHypothesis(fit, c('debt=spouse2')) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 결과의 저장 ------- \033[0m", '\n')
cat("  sink('결과저장.txt')  ", '\n')
cat("    ……  ", '\n')
cat("  sink()  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## wide format -> long format ------- \033[0m ", '\n')
cat("  df2<-reshape(df, idvar='id', varying=c(3:7), v.names='y', direction='long')  ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 변수의 순서변경 -------\033[0m ", '\n')
cat("  df%>%relocate(satprice , .after=id) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## 회귀분석 formula ------- \033[0m", '\n')
cat("  결과<-lm(소득~ . , data=Ada)   \033[1;31m모든변수 선택\033[0m ", '\n')
cat("  결과<-lm(소득~ . -1 - 학교소속감, data=Ada)   \033[1;31m변수제외\033[0m  ", '\n')
cat("  결과<-lm(소득~ 학교소속감:성별, data=Ada)   \033[1;31m상호작용항\033[0m  ", '\n')
cat("  결과<-lm(소득~ 학교소속감 * 성별, data=Ada)   \033[1;31m모든변수 + 모든상호작용\033[0m  ", '\n')
cat("  결과<-lm(소득~ I(학업탈진+성별-10), data=Ada)   \033[1;31m괄호내 수식에 따라 변수 생성\033[0m  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  df$gender2<-ifelse(df$gender==1, 1, 0) ", '\n')
cat(" \033[1;31m gender변수가1이면 gender2를 1로, 그렇지 않으면 0으로 코딩\033[0m  ", '\n')
cat("   ", '\n')

} }

