e_datamining<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("## csv파일 로딩하기 ------- ", '\n')
cat("  library(tidyverse) ", '\n')
cat("  df<-read.csv(file.choose(), skip=1, header=T, fileEncoding='CP949', encoding='UTF-8') ", '\n')
cat("   ", '\n')
cat("## Excel파일 로딩하기 ------- ", '\n')
cat("  library(readxl) ", '\n')
cat("  df<-read_excel(file.choose(), skip=1) ", '\n')
cat("   ", '\n')
cat("  df<-BasicData #내장 데이터셋 사용 ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 통계분석 시 자료에 NA가 있으면, na.rm=T 사용 -------   ", '\n')
cat("  mean(df$inc, na.rm=T)  ", '\n')
cat("  sd(df$inc, na.rm=T) ", '\n')
cat("  df%>%summarize(평균=mean(inc), na.rm=T)   ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 일부 변수를 선택해 새데이터셋 만들기 ------- ", '\n')
cat("  index <- c(2,4:6) ", '\n')
cat("  df2 <- df[ , index] ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 데이터셋의 특정 변수 지우기 ------- ", '\n') 
cat("  df <- df[ , -c(2, 4:5)] ", '\n')
cat("   ", '\n')
cat("## 자료를 솎아내서 새데이터 만들기 ------- ", '\n')
cat("  df2 <- df[ complete.cases(df$conv, df$satprice, df$age), ]  ", '\n')
cat("  df2 <- df[ df$debtratio !=Inf , ] ", '\n')
cat("  df2 <- df[ !is.na(df$debtratio) , ] ", '\n')
cat("  df2 <- df[ df$debtratio <= 124 , ] ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  library(aj412s) ", '\n')
cat("## Recoding variable values -------- ", '\n')
cat("  df<-recoding(df, 7) ", '\n')
cat("   ", '\n')
cat("## Grouping변수 만들기 ------- ", '\n')
cat("  cn<-quantile(df$inc, c(.25, .5, .75) , na.rm=T) ", '\n')
cat("  df <- mkgroup(df, 3, cn) ", '\n')
cat("   ", '\n')
cat("  cn<-c(200, 300, 400, 500) ", '\n')
cat("  df <- mkgroup(df, 3, cn) ", '\n')
cat("   ", '\n')
cat("## 문자 레코드를 숫자로 바꾸기 -------- ", '\n')
cat("  df$brand2<-c2n(df$brand) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 코드값 재코딩 ------- ", '\n')
cat("  library(aj412s) ", '\n')
cat("  ## 방법1 --- ", '\n')
cat("  df<-recoding(df, 7) ", '\n')
cat("  ## 방법2 --- ", '\n')
cat("  df$gender2[df$gender==1] <- 1 #gender의 코딩값을 재코딩해 gender2로 저장 ", '\n')
cat("  df$gender2[df$gender==2] <- 0 ", '\n')
cat("  df[df==''] <- NA  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 변수명 변경 ------- ", '\n')
cat("  df2<-BasicData[,c(1,3,7:10)] ", '\n')
cat("  colnames(df2)<-c('id','brand','conv','satprice','age','gender') ", '\n')
cat("  colnames(df2)[6]<-c('성별') ", '\n')
cat("   ", '\n')
cat("## 더미변수 만들기(mkdum사용) ------- ", '\n')
cat("  library(aj412s)  ", '\n')
cat("  df<-mkdum(df, 11) #edu변수를 더미변수로", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 자료수 확인 ------- ", '\n')
cat("  sum(is.na(df$conv))  ", '\n')
cat("  sum(!is.na(df$conv))  ", '\n')
cat("  sum(df$brand=='Ford') ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## xtabs를 사용해 막대그래프 그리기 ------- ", '\n')
cat("  xtabs(~df$gender+df$brand)  ", '\n')
cat("  barplot(xtabs(~df$gender+df$brand), beside=T, horiz=F, ylab='빈도수')  ", '\n')
cat("   ", '\n')


invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 자료의 Sampling ------- ", '\n')
cat("  index2<-sample(nrow(df), 6, replace=F) ", '\n')
cat("  샘플데이터[index2 , ] ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## density그래프 그리기 ------- ", '\n')
cat("  ggplot(df, aes(x=inc)) + geom_density() ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## dplyr사용법 ------- ", '\n')
cat("   ", '\n')
cat("  df %>% group_by(브랜드)  ", '\n')
cat("        %>% summarize(편의성평균=mean(conv, na.rm=T), 표준편차=sd(conv, na.rm=T), 자료수=n(), .groups='drop_last')  ", '\n')
cat("   ", '\n')
cat("  df %>% select(brand, gender) ", '\n')
cat("   ", '\n')
cat("  df %>% filter(변수E==2015 & (변수F=='C' | 변수F=='G') ) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## df$시군구 변수에서 용인수지구 단어가 있는 레코드를 솎아내기 --------", '\n')
cat("  df%>%filter( grepl('용인수지구' , df$시군구)) ", '\n')
cat("   ", '\n')
cat("## 상현동 아파트들 중 상떼빌 아파트만 솎아내기 -------- ", '\n')
cat("  df%>%filter( grepl('상현동', df$시군구) & grepl('상떼빌', df$단지명)) ", '\n')
cat("   ", '\n')
cat("  df<-df %>% arrange(연령대) ", '\n')
cat("   ", '\n')
cat("  df<-rename(df, 새변수명=편의성) ", '\n')
cat("   ", '\n')
cat("  NEWDATA<-merge(data1, data2, by='index') %>% merge(data3, by='index') ", '\n')
cat("      ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## subset명령문활용 -------- ", '\n')
cat("  subset(df, 평형==32, select=c(date0, 평당매매가평균)) ", '\n')
cat("  subset(df, (brand=='KIA' | brand=='GM') ,select=c(1,2,3,4)) ", '\n')
cat("  subset(df, grepl('KI', df$brand) ,select=c(1,2,3,4)) ", '\n')
cat("   ", '\n')
cat("## subset으로 32평의 평당매매가평균을 하나의 그래프로 그리기 -------- ", '\n')
cat("  plot(subset(df, 평형==32, select=c(date0, 평당매매가평균)), type='l', ", '\n')
cat("       col='cornflowerblue', lwd=2, ylim=c(1000, 2800)) ", '\n')
cat("  par(new=T) ", '\n')
cat("   ", '\n')
cat("## subset을 이용해 특정 레코드만 솎아내서 회귀분석하기 -------- ", '\n')
cat("  결과 <- lm(거래금액~전용면적+층, data=df, subset=c(year==2021 & 평형==32)  ) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  numeric 데이터로 한꺼번에 바꾸기 --------  ", '\n')
cat("  index<-c(2:4) ", '\n')
cat("  df[ ,index]<-lapply(df[,index], as.numeric) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  확률 및 p값 -------- ", '\n')
cat("  t분포 경계값: qt(확률, n-1)  ", '\n')
cat("  t분포 p값찾기: 1-pt(t검정통계량, n-1)  ", '\n')
cat("  카이자승 경계값: qchisq(확률, 자유도)  ", '\n')
cat("  카이자승 p값찾기: 1-pchisq(카이자승_검정통계량, 자유도)  ", '\n')
cat("  F분포 경계값: qf(확률, 자유도1, 자유도2)  ", '\n')
cat("  F분포 p값찾기: 1-pf(F검정통계량, k-1, n-k)  ", '\n')
cat("  정규분포 경계값: qnorm(확률)  ", '\n')
cat("  정규분포 p값찾기: 1-pnorm(z검정통계량)  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## wald test ------   ", '\n')
cat("  fit<-lm(inc~debt+house+spouse2, data=Adata) ", '\n')
cat("  linearHypothesis(fit, c('debt=3', 'spouse2+debt3<=10')) ", '\n')
cat("  linearHypothesis(fit, c('debt=spouse2')) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 결과의 저장 ------- ", '\n')
cat("   ", '\n')
cat("  sink('결과저장.csv')  ", '\n')
cat("    ……  ", '\n')
cat("  sink()  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("## 화면 스크롤 갯수 확대 & 미싱데이터 채우기 ------- ", '\n')
cat("  options(max.print=1000000)  ", '\n')
cat("  zoo::na.locf(df)  ", '\n')
cat("   ", '\n')

} }

