e_ftest<-function(explaining=0){
if(explaining==0) {
cat("   ", '\n')
cat("  # 데이터 생성 ", '\n')
cat("  # 그룹별로 각각 평균이 10, 15, 20인 데이터를 생성 ", '\n')
cat("  group_A <- c(10, 12, 11, 13, 10) ", '\n')
cat("  group_B <- c(14, 16, 15, 17, 15) ", '\n')
cat("  group_C <- c(20, 22, 19, 21, 20) ", '\n')
cat("   ", '\n')
cat("  # 분석하기 좋게 데이터 프레임으로 합침 ", '\n')
cat("  df <- data.frame( ", '\n')
cat("    height = c(group_A, group_B, group_C), ", '\n')
cat("    fertilizer = rep(c('A', 'B', 'C'), each = 5) ", '\n')
cat("    ) ", '\n')
cat("   ", '\n')
cat("  # 그룹 변수는 반드시 factor(범주형) 처리를 해주는 것이 편함 ", '\n')
cat("  df$fertilizer <- as.factor(df$fertilizer) ", '\n')
cat("   ", '\n')
cat("  # ANOVA 모델 생성 ", '\n')
cat("  anova_result <- aov(height ~ fertilizer, data = df) ", '\n')
cat("   ", '\n')
cat("  # 결과 요약 (F값과 p-value 확인) ", '\n')
cat("  summary(anova_result) ", '\n')
cat("   ", '\n')
cat("  # 사후 검정 수행 ", '\n')
cat("  TukeyHSD(anova_result) ", '\n')
cat("   ", '\n')
cat("  # 기본 그래프 ", '\n')
cat("  boxplot(height ~ fertilizer, data = df, ", '\n')
cat("          main = '비료 종류별 식물 성장 비교', ", '\n')
cat("          xlab = '비료 종류', ylab = '성장 높이',", '\n')
cat("          col = c('lightblue', 'lightgreen', 'pink'))", '\n')
cat("   ", '\n')
cat("  # 잔차(오차)에 대한 정규성 검정 (p > 0.05여야 만족) ", '\n')
cat("  shapiro.test(resid(anova_result)) ", '\n')
cat("   ", '\n')
cat("  # 등분산 검정 (p > 0.05여야 만족) ", '\n')
cat("  bartlett.test(height ~ fertilizer, data = df) ", '\n')
cat("   ", '\n')
}}

