e_ggplot2<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("\033[1;31m# ---- 산포도 with ggplot -------------------\033[0m ", '\n')
cat("  library(ggthemes); library(ggplot2) ", '\n')
cat("  Adata<-AccountBalance ", '\n')
cat("  Adata$index<-as.factor(Adata$index) ", '\n')
cat("  Adata$import<-Adata$Import; Adata$export<-Adata$Export; Adata$profit<-Adata$Profit ", '\n')
cat("   ", '\n')
cat("\033[1;31m  It is possible to include the following commands: 'geom_smooth()' and 'geom_line()' \033[0m  ", '\n')
cat("   ", '\n')
cat("  ggplot(data=Adata, aes(x=import, y=profit, shape=index, col=index)) + geom_point(size=3) ", '\n')
cat("  ggplot(data=Adata, aes(x=export, y=profit, shape=index, col=index)) + geom_point(size=3) ", '\n')
cat("   ", '\n')
cat("  ggplot(data=df, aes(x=index00, y=kospi)) + geom_line() + geom_point()  + ", '\n')
cat("      theme_stata(scheme='s2color') + labs(x='시간', y='코스피지수', title='코스피지수의 변화') ", '\n')
cat("   ", '\n')
cat("  ggplot(data=df, aes(x=index00, y=kospi)) + geom_line(col='black') + geom_point(col='steelblue')  ", '\n') +
cat("      theme_gdocs() + labs(x='시간', y='코스피지수', title='코스피지수의 변화') ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("\033[1;31m# 막대그래프 with ggplot -------------------\033[0m ", '\n')
cat(" \033[1;31m막대그래프 오름차순: ggplot(data=경상수지, aes(x=reorder(year, -경상수지평균), y=경상수지평균)) ... )\033[0m ", '\n')
cat(" \033[1;31m막대그래프 내림차순: ggplot(data=경상수지, aes(x=reorder(year, 경상수지평균), y=경상수지평균)) ... )\033[0m ", '\n')
cat("   ", '\n')
cat("library(ggplot2) ", '\n')
cat("  xx<-c('30세이하', '30대', '40대', '50대', '60세이상') ", '\n')
cat("  yy<-c(90.6, 81.5, 73.2, 69.4, 65) ", '\n')
cat("  df<-data.frame(xx,yy) ", '\n')
cat("     ", '\n')
cat("\033[1;31m# X축을 factor로 지정해야만 X값이 지정한 순서대로 출력된다\033[0m ", '\n')
cat("  df$xx <- factor(df$xx,levels=c('30세이하','30대','40대','50대','60세이상')) ", '\n')
cat("   ", '\n')
cat("  p<-ggplot(data=df, aes(x=xx, y=yy), width=0.7) +  ", '\n')
cat("  \033[1;31m셋업\033[0m       geom_bar(stat='identity', fill='steelblue', col='black') +  ", '\n')
cat("  \033[1;31mX값\033[0m        theme(axis.text.x=element_text(size= 12 , angle=-40) ) + ", '\n')
cat("  \033[1;31mY값\033[0m        theme(axis.text.y=element_text(size= 12) ) + ", '\n')
cat("  \033[1;31mY값 자리수\033[0m scale_y_continuous(labels =scales:: comma) + ", '\n')
cat("  \033[1;31m제목\033[0m       labs(title='선호부동산(%)', x='나이', y='투자선호부동산-국내주거') + ", '\n')
cat("  \033[1;31m제목 크기\033[0m  theme(title=element_text(size=16 , face='bold')) + ", '\n')
cat("  \033[1;31mX축명크기\033[0m  theme(axis.title.x = element_text(size= 14 , face='bold')) + ", '\n')
cat("  \033[1;31mY축명크기\033[0m  theme(axis.title.y = element_text(size= 14 , face='bold')) + ", '\n')
cat("  \033[1;31m막대값표시\033[0m geom_text(data=df, aes(y=yy, label = round(yy, 0) , vjust=-1, size=10) ) + ", '\n')
cat("  \033[1;31m범례삭제\033[0m   theme(legend.position = 'none') + ", '\n')
cat("  \033[1;31mY축범위\033[0m    ylim(0, 100)  ", '\n')
cat("   ", '\n')
cat("\033[1;31m# 백그라운드 지정\033[0m ", '\n')
cat("  p+theme(panel.background = element_rect(fill = 'white', color = 'black'),  ", '\n')
cat("          panel.grid.major = element_line(color = 'black', linetype = 'dotted'), ", '\n')
cat("          panel.grid.minor = element_line(color = 'black',  linetype = 'dotted' )) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("\033[1;31m# 직선 그리기 --------\033[0m ", '\n')
cat("  library(dplyr); library(aj412s); library(ggplot2) ", '\n')
cat("  \033[1;31m# KoreaMacro 변수명 재정의\033[0m ", '\n')
cat("  df<-KoreaMacro ", '\n')
cat("  df<-as.data.frame(df) ", '\n')
cat("  colnames(df)<-c('index', 'yearmonth', 'currency', 'cd91', 'bond3yr', 'kospi', 'surplus') ", '\n')
cat("   ", '\n')
cat("\033[1;31m# 직선 그리기를 위한 데이터작업 시작 --------\033[0m ", '\n')
cat("  df<-mkdate_form(df, 2)  ", '\n')
cat("  colnames(df)[8]<-'yearmonth2' ", '\n')
cat("  df$year<-substring(df$yearmonth2, 1,4) ", '\n')
cat("  df$month<-substring(df$yearmonth2, 6,7) ", '\n')
cat("  df$year<-as.numeric(df$year) ", '\n')
cat("  df$month<-as.numeric(df$month) ", '\n')
cat("  코스피<-df%>%group_by(year)%>%summarize(KOSPI평균=mean(kospi))  ", '\n')
cat("\033[1;31m# 직선 그리기를 위한 데이터작업 끝남 --------\033[0m ", '\n')
cat("  ", '\n')
cat("  ggplot(data=코스피, aes(x=year, y=KOSPI평균)) +  ", '\n')
cat("  \033[1;31m직선 셋업\033[0m  geom_line(group=1, col='red', linewidth=1) + ", '\n')
cat("  \033[1;31m점 셋업\033[0m    geom_point(col='red', size=3.0) + ", '\n')
cat("  \033[1;31my값 표시\033[0m   geom_text( data=코스피, aes(y=KOSPI평균, label = round(KOSPI평균,0), vjust=-1, size=4) ) + ", '\n')
cat("  \033[1;31mx축값 표시\033[0m theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) + ", '\n')
cat("  \033[1;31my축값 표시\033[0m theme(axis.text.y=element_text(color='black', size=13)) + ", '\n')
cat("  \033[1;31my축값 자리수\033[0m scale_y_continuous(labels =scales:: comma) + ", '\n')
cat("  \033[1;31m제목 크기\033[0m  theme(title=element_text(size= 30 , face='bold')) + ", '\n')
cat("  \033[1;31my축명크기\033[0m  theme(axis.title.y = element_text(size= 25 ,face='bold')) + ", '\n')
cat("  \033[1;31mx축명크기\033[0m  theme(axis.title.x = element_text(size= 25 ,face='bold')) + ", '\n')
cat("  \033[1;31mxy축/제목 타이틀\033[0m labs(x='연도', y='연간 코스피평균', title='연도별 코스피평균') + ", '\n')
cat("  \033[1;31m범례제목 삭제\033[0m theme(legend.position = 'none') ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# \033[1;31m2개의 직선 그리기 --------\033[0m ", '\n')
cat("# \033[1;31m선종류 : blank, solid, dashed, dotted, dotdash, longdash, twodash\033[0m ", '\n')
cat("   ", '\n')
cat("library(ggplot2) ", '\n')
cat("  df <- data.frame( x = 1:5, y1 = c(2, 4, 6, 8, 10), y2 = c(1, 3, 5, 7, 9) ) ", '\n')
cat("   ", '\n')
cat("  plot <- ggplot(df, aes(x = x)) + ", '\n')
cat("          geom_line(aes(y = y1), color = 'blue', linetype = 'solid') + ", '\n')
cat("          geom_line(aes(y = y2), color = 'red',  linetype = 'dashed')  ", '\n')
cat("   ", '\n')
cat("  plot <- plot + labs( ", '\n')
cat("           title = 'Two Lines on One Graph', ", '\n')
cat("           x = 'X-axis Label', ", '\n')
cat("           y = 'Y-axis Label' ) + theme_minimal() ", '\n')
cat("  print(plot) ", '\n')
cat("   ", '\n')
cat("# \033[1;31m stata_theme을 사용한 2개의 직선 그리기 --------\033[0m ", '\n')
cat("  library(ggthemes) ", '\n')
cat("  plot <- plot + labs( ", '\n')
cat("           title = 'Two Lines on One Graph', ", '\n')
cat("           x = 'X-axis Label', ", '\n')
cat("           y = 'Y-axis Label' ) + theme_stata(scheme='s1color')  ", '\n')
cat("  print(plot) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("\033[1;31m# 히스토그램 with jmv and ggplot -------------------\033[0m ", '\n')
cat("  df<-interest ", '\n')
cat("  jmv::descriptives(data = interest, vars = LoanInterest, hist=TRUE, dens=TRUE) ", '\n')
cat("  ggplot(data=df, aes(x=LoanInterest)) + geom_histogram(bins=40) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m#facet_wrap의 활용 --------\033[0m ", '\n')
cat("library(ggplot2); library(ggthemes) ", '\n')
cat("  df<-mtcars ", '\n')
cat("  ggplot(df, aes(y=gear) ) + geom_bar(fill='salmon3') + ", '\n')
cat("        labs(x='Count', y='Gear', title='기어의 갯수') + ", '\n')
cat("        facet_wrap(~am) + theme_stata( scheme='s2color') + ", '\n')
cat("        coord_flip() ", '\n')
cat("   ", '\n')
cat("  ggplot(df, aes(x=mpg, y=hp) ) + theme_stata(scheme='s2color') +", '\n')
cat("        geom_line() +geom_point() +", '\n')
cat("        labs(x='MPG', y='HP(Horse Power)', title='MPG와 HP') +", '\n')
cat("        facet_wrap(~am) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("\033[1;31m#Panel Data --------\033[0m    ", '\n')
cat("  library(gplots); library(plm)    ", '\n')
cat("  Grunfedl<-data(package='plm', 'Grunfeld')    ", '\n')
cat("  Gdata<-Grunfeld    ", '\n')
cat("  plotmeans(Gdata$inv~Gdata$firm)   ", '\n')
cat("  plotmeans(Gdata$inv~Gdata$year)   ", '\n')
cat("    ", '\n')
cat("\033[1;31m#시계열분석 --------\033[0m ", '\n')
cat("  AccountBalance <- ts(AccountBalance, start=c(2015,1), frequency=4) ", '\n')
cat("  forecast::autoplot(AccountBalance[ ,c('Export','Profit')], facets=TRUE )  # forecast패키지  ", '\n') 
cat("  forecast::ggseasonplot(AccountBalance[,'Import'], year.labels = TRUE, year.labels.left=TRUE)  # forecast패키지  ", '\n')
cat("  forecast::ggsubseriesplot(AccountBalance[,'Export'])  # forecast패키지  ", '\n')
cat("  ", '\n')

}}