e_ggplot1<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("library(ggplot2) ", '\n')
cat("library(car) #교수연봉 데이터 ", '\n')
cat(" ", '\n')
cat("ggplot(data=mtcars, aes(x=wt, y=mpg)) +  ", '\n')
cat("  geom_point(pch=17, color='blue', size=2) +  ", '\n')
cat("  geom_smooth(method='lm', color='red', linetype=2) + ", '\n')
cat("  labs(title='Automobile Data', x='Weight', y='Miles Per Gallon') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Label지정 및 파세트 그리드 -------\033[0m ", '\n')
cat("mtcars$am <- factor( mtcars$am, levels=c(0,1),  labels=c('Automatic', 'Manual') ) ", '\n')
cat("mtcars$vs <- factor( mtcars$vs, levels=c(0,1), labels=c('V-Engine', 'Straight Engine') ) ", '\n')
cat("mtcars$cyl <- factor(mtcars$cyl) ", '\n')
cat(" ", '\n')
cat("ggplot(data=mtcars, aes(x=hp, y=mpg, shape=cyl, color=cyl)) + ", '\n')
cat("  geom_point(size=3) +  ", '\n')
cat("  facet_grid(am~vs) +  ", '\n')
cat("  labs(title='Automobile Data by Engine Type',  ", '\n')
cat("            x='Horsepower', y='Miles Per Gallon') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Box plot / Geom Point / Geom Rug ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=rank, y=salary)) + ", '\n')
cat("  geom_boxplot(fill='cornflowerblue',color='black', notch=TRUE) + ", '\n')
cat("  geom_point(position='jitter', color='blue', alpha=0.5) + ", '\n')
cat("  geom_rug(color='black') ", '\n')
cat(" ", '\n')
cat("library(lattice) #성악가 데이터  ", '\n')
cat("ggplot(singer, aes(x=voice.part, y=height)) + geom_boxplot() ", '\n')
cat(" ", '\n')
cat("ggplot(singer, aes(x=voice.part, y=height)) + ", '\n')
cat("  geom_violin(fill='lightblue') + ", '\n')
cat("  geom_boxplot(fill='lightgreen', width=.2) + ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 3개 밀도함수를 겹치게 그리기 ------\033[0m ", '\n') 
cat("ggplot(data=Salaries, aes(x=salary, fill=rank)) + ", '\n')
cat("  geom_density(alpha=.3) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 범례Legend 사용법 ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=yrs.since.phd, y=salary, color=rank, shape=sex)) + ", '\n')
cat("  geom_point()  ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# 밀도함수 ------\033[0m ", '\n')
cat("ggplot(data=Salaries, aes(x=salary, fill=rank)) + ", '\n')
cat("  geom_density(alpha=.3) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 범례Legend 사용법 ------\033[0m ", '\n') 
cat("ggplot(Salaries, aes(x=yrs.since.phd, y=salary, color=rank, shape=sex)) + ", '\n')
cat("  geom_point() ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Box Plot and Data Distribution ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=rank, y=salary)) + ", '\n')
cat("  geom_boxplot(fill='cornflowerblue',color='black', notch=TRUE) + ", '\n')
cat("  geom_point(position='jitter', color='blue', alpha=0.5) + ", '\n')
cat("  geom_rug(color='black') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# 막대그래프 Count : Stacking ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=rank, fill=sex)) + ", '\n')
cat("  geom_bar(position='stack') + ", '\n')
cat("  labs(title='position=stack') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 막대그래프 Count : Side Arrange ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=rank, fill=sex)) + ", '\n')
cat("  geom_bar(position='dodge') + ", '\n')
cat("  labs(title='position=dodge') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 막대그래프 Percent ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=rank, fill=sex)) + ", '\n')
cat("  geom_bar(position='fill') + ", '\n')
cat("  labs(title='position=fill') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# 파세트 랩 : facet_wrap(~var, nrow=n) ------\033[0m ", '\n')
cat("library(lattice) ", '\n')
cat("ggplot(data=singer, aes(x=height)) + ", '\n')
cat("  geom_histogram() + ", '\n')
cat("  facet_wrap(~voice.part, nrow=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 파세트 그리드 ------\033[0m ", '\n')
cat("  facet_grid(rowvar~colvar) ", '\n')
cat("  facet_grid(rowvar~.) ", '\n')
cat("  facet_grid(.~colvar) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 파세트 그리드1 ------\033[0m ", '\n')
cat("ggplot(Salaries, aes(x=yrs.since.phd, y=salary, color=rank, shape=rank)) +  ", '\n')
cat("  geom_point() +  ", '\n')
cat("  facet_grid(.~sex) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# 파세트 그리드2 ------\033[0m ", '\n')
cat("ggplot(data=singer, aes(x=height, fill=voice.part)) + ", '\n')
cat("  geom_density() + ", '\n')
cat("  facet_grid(voice.part~.) ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Point에 직선 그리기 ------\033[0m ", '\n')
cat("ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary, ", '\n')
cat("  linetype=sex, shape=sex, color=sex)) + ", '\n')
cat("  geom_smooth(method=lm, formula=y~poly(x,2), se=FALSE, size=1) + ", '\n')
cat("  geom_point(size=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Y축 Scale 및 X축 Label ------\033[0m ", '\n')
cat("ggplot(data=Salaries, aes(x=rank, y=salary, fill=sex)) + ", '\n')
cat("  geom_boxplot() + ", '\n')
cat("  scale_x_discrete(breaks=c('AsstProf', 'AssocProf', 'Prof'),  ", '\n')
cat("                   labels=c('Assistant_Professor', ", '\n')
cat("                            'Associate_Professor', ", '\n')
cat("                            'Full_Professor')) + ", '\n')
cat("  scale_y_continuous(breaks=c(50000, 100000, 150000, 200000), ", '\n')
cat("                     labels=c('$50K', '$100K', '$150K', '$200K')) + ", '\n')
cat("  labs(title='Faculty Salary by Rank and Sex', x='', y='') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Bubble Chart ------\033[0m ", '\n')
cat("ggplot(mtcars, aes(x=wt, y=mpg, size=disp)) + ", '\n')
cat("     geom_point(shape=21, color='black', fill='cornsilk') + ", '\n')
cat("     labs(x='Weight', y='Miles Per Gallon', title='Bubble Chart', size='Engine\nDisplacement') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# colors : Set1, Set2, Set3, Pastel1, Pastel2, Paired, Dark2, Accent ------\033[0m ", '\n')
cat("ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary, color=rank)) + ", '\n')
cat("  scale_color_brewer(palette='Accent') + ", '\n')
cat("  geom_point(size=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# colors : My definition ------\033[0m ", '\n') 
cat("ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary, color=rank)) + ", '\n')
cat("    scale_color_manual(values=c('orange', 'olivedrab', 'navy')) + ", '\n')
cat("    geom_point(size=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Multiple graphs per page ------\033[0m ", '\n')
cat("  p1 <- ggplot(data=Salaries, aes(x=rank)) + geom_bar()  ", '\n')
cat("  p2 <- ggplot(data=Salaries, aes(x=sex)) + geom_bar()  ", '\n')
cat("  p3 <- ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary)) + geom_point() ", '\n')
cat("  grid.arrange(p1, p2, p3, ncol=3) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Dot Chart 그리기 ------\033[0m ", '\n') 
cat("  x <- mtcars[order(mtcars$mpg),]  ", '\n')
cat("  x$cyl <- factor(x$cyl)  ", '\n')
cat("  x$color[x$cyl==4] <- 'red'  ", '\n')
cat("  x$color[x$cyl==6] <- 'blue' ", '\n')
cat("  x$color[x$cyl==8] <- 'darkgreen' ", '\n')
cat("  dotchart(x$mpg,  ", '\n')
cat("                   labels = row.names(x), ", '\n')
cat("  		 cex=.7,  ", '\n')
cat("  		 groups = x$cyl,  ", '\n')
cat("  		 gcolor = 'black',  #group color ", '\n')
cat("  		 color = x$color, ", '\n')
cat("  		 pch=19, ", '\n')
cat("  		 main = 'Gas Mileage for Car Models_grouped by cylinder',  ", '\n')
cat("  		 xlab = 'Miles Per Gallon') ", '\n')
cat("   ", '\n')
}}


