e_ggplot<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("# ---- 막대그래프 그리기 1 ------------------- ", '\n')
cat("  df_x<-c('30세이하', '30대', '40대', '50대', '60세이상') ", '\n')
cat("  df_y<-c(90.6, 81.5, 73.2, 69.4, 65) ", '\n')
cat("  df_data<-data.frame(df_x,df_y) ", '\n')
cat("   ", '\n')
cat("  # X축을 factor로 지정해야만 X값이 순서대로 출력된다. 그렇지 않으면 30대, 30세이하 ... 순으로 출력된다 ", '\n')
cat("   ", '\n')
cat("  df_data$df_x<-factor(df_data$df_x, levels=c('30세이하', '30대', '40대', '50대', '60세이상') ) ", '\n')
cat("   ", '\n')
cat("  ggplot(data=df_data, aes(x=df_x, y=df_y)) ", '\n')
cat("    + geom_bar(stat='identity', fill='purple', col='black')  ", '\n')
cat("    + theme(axis.text.y=element_text(size=16) )  ", '\n')
cat("    + theme(axis.text.x=element_text(size=16, angle=-40) )  ", '\n')
cat("    + labs(x='연령', y='투자선호부동산:국내주거', title='연령별 투자선호부동산(%)')  ", '\n')
cat("    + theme(title=element_text(size=25, face='bold'))  ", '\n')
cat("    + theme(axis.title.x = element_text(size=20,face='bold'))  ", '\n')
cat("    + theme(axis.title.y = element_text(size=20, face='bold'))  ", '\n')
cat("    + geom_text( data=df_data, aes(y=df_y, label = round(df_y, 0) , vjust=-1, size=10) ) ", '\n')
cat("    + theme(legend.position = 'none') ", '\n')
cat("  ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# ---- 막대그래프 그리기 2 ------------------- ", '\n')
cat("  library(dplyr); library(aj412s); library(ggplot2) ", '\n')
cat("  # KoreaMacro 변수명 재정의 ", '\n')
cat("  df<-KoreaMacro ", '\n')
cat("  df<-as.data.frame(df) ", '\n')
cat("  colnames(df)<-c('index', 'yearmonth', 'currency', 'cd91', 'bond3yr', 'kospi', 'surplus') ", '\n')
cat("   ", '\n')
cat("  df<-mkdate_form(df, 2)  ", '\n')
cat("  colnames(df)[8]<-'yearmonth2' ", '\n')
cat("  df$year<-substring(df$yearmonth2, 1,4) ", '\n')
cat("  df$month<-substring(df$yearmonth2, 6,7) ", '\n')
cat("  df$year<-as.numeric(df$year) ", '\n')
cat("  df$month<-as.numeric(df$month) ", '\n')
cat(" ", '\n')
cat("  경상수지<-df%>%group_by(year)%>%summarize(경상수지평균=mean(surplus)) ", '\n')
cat(" ", '\n')
cat("  # 오름차순: ggplot(data=경상수지, aes(x=reorder(year, -경상수지평균), y=경상수지평균)) ... ) ", '\n')
cat("  # 내림차순: ggplot(data=경상수지, aes(x=reorder(year, 경상수지평균), y=경상수지평균)) ... ) ", '\n')
cat(" ", '\n')
cat("  ggplot(data=경상수지, aes(x=year, y=경상수지평균))  ", '\n')
cat("  셋업 +geom_bar(stat='identity', fill='steelblue', col='black')  ", '\n')
cat("  막대에 값표시 +geom_text( data=경상수지, aes(y=경상수지평균, label = round(경상수지평균,0), vjust=-1, size=4) )  ", '\n')
cat("  x축값 표시 +theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("  y축값 표시 +theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("  y축값 자리수 +scale_y_continuous(labels =scales:: comma) ", '\n')
cat("  제목 크기 +theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("  x축명크기 +theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("  y축명크기 +theme(axis.title.y = element_text(size=25,face='bold'))  ", '\n')
cat("  xy축/제목 타이틀 +labs(x='연도', y='경상수지평균', title='연도별 경상수지평균')  ", '\n')
cat("  범례제목 삭제 +theme(legend.position = 'none')  ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# ---- 직선 그리기 -------------------- ", '\n')
cat("  ", '\n')
cat("# geom_line(data=df, mapping=aes(x=컬럼이름X,  ", '\n')
cat("#                             y=컬럼이름Y,  ", '\n')
cat("#                             group=컬럼이름K,  ", '\n')
cat("#                             linetype=컬럼이름K,  ", '\n')
cat("#                             color=컬럼이름K),  ", '\n')
cat("#	          	     		   linewidth=숫자A, ...)  ", '\n')
cat("  ", '\n')
cat("  library(dplyr); library(aj412s); library(ggplot2) ", '\n')
cat("  # KoreaMacro 변수명 재정의 ", '\n')
cat("  df<-KoreaMacro ", '\n')
cat("  df<-as.data.frame(df) ", '\n')
cat("  colnames(df)<-c('index', 'yearmonth', 'currency', 'cd91', 'bond3yr', 'kospi', 'surplus') ", '\n')
cat("   ", '\n')
cat("  df<-mkdate_form(df, 2)  ", '\n')
cat("  colnames(df)[8]<-'yearmonth2' ", '\n')
cat("  df$year<-substring(df$yearmonth2, 1,4) ", '\n')
cat("  df$month<-substring(df$yearmonth2, 6,7) ", '\n')
cat("  df$year<-as.numeric(df$year) ", '\n')
cat("  df$month<-as.numeric(df$month) ", '\n')
cat("  코스피<-df%>%group_by(year)%>%summarize(KOSPI평균=mean(kospi))  ", '\n')
cat("  ", '\n')
cat("  ggplot(data=코스피, aes(x=year, y=KOSPI평균))  ", '\n')
cat("  직선 셋업 +geom_line(group=1, col='red', linewidth=1)  ", '\n')
cat("  점 셋업 +geom_point(col='red', size=3.0)  ", '\n')
cat("  y값 표시 +geom_text( data=코스피, aes(y=KOSPI평균, label = round(KOSPI평균,0), vjust=-1, size=4) )  ", '\n')
cat("  x축값 표시 +theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("  y축값 표시 +theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("  y축값 자리수 +scale_y_continuous(labels =scales:: comma)  ", '\n')
cat("  제목 크기 +theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("  y축명크기 +theme(axis.title.y = element_text(size=25,face='bold'))  ", '\n')
cat("  x축명크기 +theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("  xy축/제목 타이틀 +labs(x='연도', y='연간 코스피평균', title='연도별 코스피평균')  ", '\n')
cat("  범례제목 삭제 +theme(legend.position = 'none')  ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("############ Panel Data ############    ", '\n')
cat("  library(plm)     ", '\n')
cat("  # Grunfeld변수: firm  year  inv  value  capital    ", '\n')
cat("  # inv: gross Investment    ", '\n')
cat("  # value: value of the firm    ", '\n')
cat("  # capital: stock of plant and equipment    ", '\n')
cat("  ", '\n')
cat("  library(gplots); library(plm)    ", '\n')
cat("  plotmeans(Grunfeld$inv~Grunfeld$firm)   ", '\n')
cat("  plotmeans(Grunfeld$inv~Grunfeld$year)   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# ---- 산포도 그리기 -------------------- ", '\n')
cat("# 내장데이터: mtcars ", '\n')
cat("# mpg=연비(hwy), cyl=엔진의 기통수, disp=배기량, hp=마력, drat=뒤차축비, wt=무게, ", '\n')
cat("# qsec=1/4mile 도달시간, vs=(0:V-엔진/1:Straight-엔진), am=변속기어(0:오토, 1=변속기어) ", '\n')
cat("# gear=전진기어 갯수, carb=캬뷰레터(기화기) 갯수 ", '\n')
cat(" ", '\n')
cat("#  ggplot(data=mpg,mapping = aes(x=displ, y=hwy)) ", '\n')
cat("#	  +geom_smooth() ", '\n')
cat("#	  +geom_point() ", '\n')
cat(" ", '\n')
cat("  mtcars$cyl <- as.factor(mtcars$cyl) ", '\n')
cat("  mtcars$gear <- as.factor(mtcars$gear) ", '\n')
cat("  ggplot(data = mtcars, aes(x=disp, y=mpg, shape=cyl, col=cyl))  ", '\n')
cat("  점 셋업 +geom_point(size=3)  ", '\n')
cat("  x축값 표시 +theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("  y축값 표시 +theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("  y축값 자리수 +scale_y_continuous(labels =scales:: comma)  ", '\n')
cat("  제목 크기 +theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("  x축명크기 +theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("  y축명크기 +theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("  xy축/제목 타이틀 +labs(x='자동차 배기량', y='자동차 연비', title='배기량 대비 연비')  ", '\n')
cat("  범례타이틀 지정 +scale_colour_discrete(name='엔진의 기통수')  ", '\n')
cat("  범례타이틀 지정 +scale_shape_discrete(name='엔진의 기통수')  ", '\n')
cat("  범례타이클 크기/범례글자 크리 +theme(legend.title=element_text(size=14), legend.text=element_text(size=10)) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# ---- 산포도 그리기 with lowess  -------------------- ", '\n')
cat("  ggplot(mtcars) ", '\n')
cat("  점 셋업 +geom_point(aes(x=disp, y=mpg, size=2.5))  ", '\n')
cat("  선 추가 +geom_smooth(aes(x=disp, y=mpg))  ", '\n')
cat("  x축값 표시 +theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5))  ", '\n')
cat("  y축값 표시 +theme(axis.text.y=element_text(color='black', size=13))  ", '\n')
cat("  y축값 자리수 +scale_y_continuous(labels =scales:: comma)  ", '\n')
cat("  제목 크기 +theme(title=element_text(size=30, face='bold'))  ", '\n')
cat("  x축명크기 +theme(axis.title.x = element_text(size=25,face='bold'))  ", '\n')
cat("  y축명크기 +theme(axis.title.y = element_text(size=25,face='bold'))  ", '\n')
cat("  xy축/제목 타이틀 +labs(x='자동차 배기량', y='자동차 연비', title='배기량 대비 연비')  ", '\n')
cat("  범례 삭제 +theme(legend.position = 'none')  ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# ---- 시계열분석 -------------------- ", '\n')
cat("  autoplot(df[ ,c('gdpgrowth','unemp')], facets=TRUE) #ggplot2패키지  ", '\n')
cat("  ggseasonplot(df[,'gdp'], year.labels = TRUE, year.labels.left=TRUE) #forecast패키지  ", '\n')
cat("  ggsubseriesplot(Adata[,'gdp']) #forecast패키지  ", '\n')

}}